services:
  backend:
    build:
      context: ./backend
    command: node --watch server.js
    ports:
      - "5555:5555"
    env_file:
      - ./backend/.env
    environment:
      PORT: 5555
      MONGO_URI: mongodb://mongo:27017/campuseventhub
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - campushub

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - campushub

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5555/api
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - campushub

networks:
  campushub:
    driver: bridge

volumes:
  mongo_data:
